spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


# Perfil de producao
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5433/imagelite